# Generated by Django 2.1.15 on 2020-08-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='awuwu',
        ),
    ]
