# Generated by Django 2.1.15 on 2020-08-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200822_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='awuwu',
            new_name='email',
        ),
    ]
